services:
  - type: web
    name: career-glide-frontend
    env: docker
    plan: free
    region: oregon
    branch: Development
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://careerglide.onrender.com/api/
